[package]
name = "mdc"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mdc"
path = "src/main.rs"

[features]
default = ["serial"]
serial = ["mdc-transport/serial"]

[dependencies]
mdc-core = { path = "../../crates/mdc-core" }
mdc-protocol = { path = "../../crates/mdc-protocol" }
mdc-transport = { path = "../../crates/mdc-transport" }
mdc-simulator = { path = "../../crates/mdc-simulator" }
image = { version = "=0.24.9", default-features = false, features = ["png", "jpeg"] }
serde = { workspace = true }
serde_json = "=1.0.100"
