[workspace]
members = ["crates/mdc-protocol", "crates/mdc-transport", "crates/mdc-core", "crates/mdc-simulator", "crates/mdc-discovery", "crates/mdc-provision", "tools/mdc-cli", "sdk/node/native"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
serde = { version = "=1.0.171", features = ["derive"] }
serde_cbor = "=0.11.2"
thiserror = "=1.0.38"
